name: Release

on:
  push:
    tags:
    - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
      
    - name: Archive CreateADPDC
      run: |
        cd active-directory && zip -r ../CreateADPDC.zip *

    - name: Archive SOFS Prep
      run: |
        cd sofs/prep && zip -r ../../PrepareSOFS.zip *

    - name: Archive SOFS Config
      run: |
        cd sofs/config && zip -r ../../ConfigSOFS.zip *

    - name: Archive SOFS Prep
      run: |
        cd cluster/prep && zip -r ../../PrepareCluster.zip *

    - name: Archive SOFS Config
      run: |
        cd cluster/config && zip -r ../../ConfigCluster.zip *

    - name: Archive Domain Member Machine Prep
      run: |
        cd member-machine/prep && zip -r ../../PrepareMemberMachine.zip *

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false
        
    - name: Upload Asset
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./CreateADPDC.zip
        asset_name: CreateADPDC.zip
        asset_content_type: application/zip
        
    - name: Upload Asset
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./PrepareSOFS.zip
        asset_name: PrepareSOFS.zip
        asset_content_type: application/zip

    - name: Upload Asset
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./ConfigSOFS.zip
        asset_name: ConfigSOFS.zip
        asset_content_type: application/zip


    - name: Upload Asset
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./PrepareCluster.zip
        asset_name: PrepareCluster.zip
        asset_content_type: application/zip

    - name: Upload Asset
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./ConfigCluster.zip
        asset_name: ConfigCluster.zip
        asset_content_type: application/zip

    - name: Upload Asset
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./PrepareMemberMachine.zip
        asset_name: PrepareMemberMachine.zip
        asset_content_type: application/zip
